// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAy8n6GHYxOmXxLfUZZQn4I_h2f1OPYb90',
    appId: '1:660579424059:web:b12b90d0d237b39fbf491e',
    messagingSenderId: '660579424059',
    projectId: 'flutter-agile-poker',
    authDomain: 'flutter-agile-poker.firebaseapp.com',
    databaseURL: 'https://flutter-agile-poker-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-agile-poker.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXvQMVoos5rnFJykypXzXIQoGeD7AGHzQ',
    appId: '1:660579424059:android:26c5d2e044b884b8bf491e',
    messagingSenderId: '660579424059',
    projectId: 'flutter-agile-poker',
    databaseURL: 'https://flutter-agile-poker-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-agile-poker.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuevlVLFjngOMmSAQ9GxETvqwiS5przmw',
    appId: '1:660579424059:ios:f550897e1509cb0fbf491e',
    messagingSenderId: '660579424059',
    projectId: 'flutter-agile-poker',
    databaseURL: 'https://flutter-agile-poker-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-agile-poker.appspot.com',
    iosClientId: '660579424059-jakdp1mos089r92jsacv57g6v93sobpq.apps.googleusercontent.com',
    iosBundleId: 'com.agilepoker.app',
  );
}
